<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ftl</string>
	</array>
	<key>name</key>
	<string>FTL</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>&lt;#--</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.ftl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>--&gt;</string>
			<key>name</key>
			<string>comment.block.ftl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>--</string>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.ftl</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;\/?)((?i:#import|#function|#macro|#compress|#if|#else|#elseif|#list|#assign|#local|#switch|#case|#break|#return)\b)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.begin.ftl</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.any.ftl</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(&gt;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.tag.end.ftl</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.any.ftl</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#tag-stuff</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.basic</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.ftl</string>
</dict>
</plist>
